// Code generated by goctl. DO NOT EDIT.
// Source: find_user_info.proto

package server

import (
	"context"

	"micro_service_user_service/find_user/internal/logic"
	"micro_service_user_service/find_user/internal/svc"
	"micro_service_user_service/protoc"
)

type FindUserInfoServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedFindUserInfoServer
}

func NewFindUserInfoServer(svcCtx *svc.ServiceContext) *FindUserInfoServer {
	return &FindUserInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *FindUserInfoServer) FindUserInfoByUserName(ctx context.Context, in *protoc.ByUserNameRequest) (*protoc.ByUserNameResponse, error) {
	l := logic.NewFindUserInfoByUserNameLogic(ctx, s.svcCtx)
	return l.FindUserInfoByUserName(in)
}

func (s *FindUserInfoServer) FindUserInfoByNickName(ctx context.Context, in *protoc.ByNickNameRequest) (*protoc.ByNickNameResponse, error) {
	l := logic.NewFindUserInfoByNickNameLogic(ctx, s.svcCtx)
	return l.FindUserInfoByNickName(in)
}

func (s *FindUserInfoServer) CheckUserMemberById(ctx context.Context, in *protoc.CheckUserMemberRequest) (*protoc.CheckUserMemberResponse, error) {
	l := logic.NewCheckUserMemberByIdLogic(ctx, s.svcCtx)
	return l.CheckUserMemberById(in)
}
