// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	goRedis "github.com/go-redis/redis/v8"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`created_at`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`"), "=?,") + "=?"
)

var (
	STATES_NORMAL       int64 = 1
	STATES_FEOZEN       int64 = 2
	STATES_CANCEL       int64 = 3
	STATES_INTERDICTION int64 = 4
	STATES_AUDIT        int64 = 5

	MEMBER_YES int64 = 1
	MEMBER_NO  int64 = 0

	USER_INFO_REDIS_KEY string = "user_info_id_"
	USER_INFO_REDIS_VALIDITY time.Duration = 60 * 60 * 24 * 1000 * 1000 * 1000
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
		FindUserInfoByUserName(ctx context.Context, user_name string) (userInfo *User, err error)
		UpdateUserStates(ctx context.Context, id int64, states int64) error
		GetUserInfoByID(ctx context.Context, id int64) (userInfo *User, err error)
		GetNormalUserInfoByID(ctx context.Context, id int64) (userInfo *User, err error)
		FindUserInfoByNickName(ctx context.Context, nickname string) (userInfo *User, err error)
		UpdateUserInfoByID(ctx context.Context, id int64, nickname string, sex int64, birthday time.Time) (user_id int64, err error)
		UpdateUserMemberByID(ctx context.Context, id int64, is_member int64) (user_id int64, err error)
		UpdateUserPassWordByID(ctx context.Context, id int64, password string) (user_id int64, err error)
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
		redisModel goRedis.ClusterClient
	}

	User struct {
		Id         int64     `db:"id"`
		UserName   string    `db:"user_name"`   // 用户名
		Password   string    `db:"password"`    // 密码
		Nickname   string    `db:"nickname"`    // 昵称
		Sex        int64     `db:"sex"`         // 性别 0:男 1:女
		Birthday   time.Time `db:"birthday"`    // 生日
		State      int64     `db:"state"`       // 状态 1:正常 2:冻结 3:注销 4:禁封 5:待审核
		IsMember   int64     `db:"is_member"`   // 是否是会员 0:否 1:是
		UpdateTime time.Time `db:"update_time"` // 更新时间
		CreateTime time.Time `db:"create_time"` // 创建时间
	}
)

func newUserModel(conn sqlx.SqlConn, redisModel goRedis.ClusterClient) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`user`",
		redisModel : redisModel,
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindUserInfoByUserName(ctx context.Context, user_name string) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `user_name` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, user_name)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) GetUserInfoByID(ctx context.Context, id int64) (*User, error) {

	var resp User
	redisKey := fmt.Sprintf("%s%d", USER_INFO_REDIS_KEY, id)
	redisData := m.redisModel.Get(ctx, redisKey)
	if redisData.Val() != ""{
		err := json.Unmarshal([]byte(redisData.Val()), &resp)
		if err == nil {
			return &resp, nil
		}
	}
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		data, _ := json.Marshal(resp)
		m.redisModel.Set(ctx, redisKey, string(data), USER_INFO_REDIS_VALIDITY)
		return &resp, nil
	case ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) GetNormalUserInfoByID(ctx context.Context, id int64) (*User, error) {

	var resp User
	redisKey := fmt.Sprintf("%s%d", USER_INFO_REDIS_KEY, id)
	redisData := m.redisModel.Get(ctx, redisKey)
	if redisData.Val() != ""{
		err := json.Unmarshal([]byte(redisData.Val()), &resp)
		if err == nil {
			return &resp, nil
		}
	}

	query := fmt.Sprintf("select %s from %s where `id` = ? and state = ? limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, 1)
	switch err {
	case nil:
		data, _ := json.Marshal(resp)
		m.redisModel.Set(ctx, redisKey, string(data), USER_INFO_REDIS_VALIDITY)
		return &resp, nil
	case ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindUserInfoByNickName(ctx context.Context, nickname string) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `nickname` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, nickname)
	switch err {
	case nil:
		return &resp, nil
	case ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) UpdateUserInfoByID(ctx context.Context, id int64, nickname string, sex int64, birthday time.Time) (user_id int64, err error) {
	query := fmt.Sprintf("update %s set `nickname` = ?, `sex` = ?, birthday = ? where id = ?", m.table)
	ret, err := m.conn.ExecCtx(ctx, query, nickname, sex, birthday, id)
	if err != nil {
		return 0, err
	}
	redisKey := fmt.Sprintf("%s%d", USER_INFO_REDIS_KEY, id)
	m.redisModel.Del(ctx, redisKey)
	lastID, _ := ret.LastInsertId()
	return lastID, err
}

func (m *defaultUserModel) UpdateUserMemberByID(ctx context.Context, id, is_member int64) (user_id int64, err error) {
	query := fmt.Sprintf("update %s set `is_member` = ? where id = ?", m.table)
	ret, err := m.conn.ExecCtx(ctx, query, is_member, id)
	if err != nil {
		return 0, err
	}
	redisKey := fmt.Sprintf("%s%d", USER_INFO_REDIS_KEY, id)
	m.redisModel.Del(ctx, redisKey)
	lastID, _ := ret.LastInsertId()
	return lastID, err
}

func (m *defaultUserModel) UpdateUserPassWordByID(ctx context.Context, id int64, password string) (user_id int64, err error) {
	query := fmt.Sprintf("update %s set `password` = ? where id = ?", m.table)
	ret, err := m.conn.ExecCtx(ctx, query, password, id)
	if err != nil {
		return 0, err
	}

	lastID, _ := ret.LastInsertId()
	return lastID, err
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserName, data.Password, data.Nickname, data.Sex, data.Birthday, data.State, data.IsMember)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, data *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserName, data.Password, data.Nickname, data.Sex, data.Birthday, data.State, data.IsMember, data.Id)
	return err
}

func (m *defaultUserModel) UpdateUserStates(ctx context.Context, id int64, states int64) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, "`states`")
	_, err := m.conn.ExecCtx(ctx, query, states, id)
	redisKey := fmt.Sprintf("%s%d", USER_INFO_REDIS_KEY, id)
	m.redisModel.Del(ctx, redisKey)
	return err
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
