// Code generated by goctl. DO NOT EDIT.
// Source: user_register.proto

package server

import (
	"context"

	"micro_service_user_service/protoc"
	"micro_service_user_service/user_rc/internal/logic"
	"micro_service_user_service/user_rc/internal/svc"
)

type UserRegisterOrCancelServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedUserRegisterOrCancelServer
}

func NewUserRegisterOrCancelServer(svcCtx *svc.ServiceContext) *UserRegisterOrCancelServer {
	return &UserRegisterOrCancelServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRegisterOrCancelServer) UserRegister(ctx context.Context, in *protoc.RegisterRequest) (*protoc.RegisterResponse, error) {
	l := logic.NewUserRegisterLogic(ctx, s.svcCtx)
	return l.UserRegister(in)
}

func (s *UserRegisterOrCancelServer) UserCancel(ctx context.Context, in *protoc.CancelRequest) (*protoc.CancelResponse, error) {
	l := logic.NewUserCancelLogic(ctx, s.svcCtx)
	return l.UserCancel(in)
}
